#==========================================
# Hugo Site Configuration
# ==========================================

# Website info
title: "Hugo Academic CV Theme"
baseURL: "https://example.com/"

# ==========================================
# Hugo Specific
# ==========================================
hugo:
  hasCJKLanguage: false
  removePathAccents: true

# ==========================================
# Languages (다국어 설정)
# ==========================================
defaultContentLanguage: ko
defaultContentLanguageInSubdir: true

languages:
  ko:
    languageName: 한국어
    weight: 1
    title: "포트폴리오"
    contentDir: content/ko
  en:
    languageName: English
    weight: 2
    title: "Portfolio"
    contentDir: content/en

# ==========================================
# Menus
# ==========================================
menu:
  main:
    - name: bio
      url: /
      weight: 10
      lang: ko
    - name: bio
      url: /
      weight: 10
      lang: en
    - name: experience
      url: /experience/
      weight: 11
      lang: ko
    - name: experience
      url: /experience/
      weight: 11
      lang: en

# ==========================================
# Params (테마 맞춤용)
# ==========================================
params:
  theme: blox
  description: "My academic portfolio"
  enableEmoji: true

# ==========================================
# Modules
# ==========================================
module:
  imports:
    - path: github.com/hugo-blox/hugo-blox-builder/

# ==========================================
# Advanced Settings
# ==========================================
build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: "<sup>^</sup>"
ignoreFiles: [\.ipynb$, \.ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep

# ==========================================
# Ignore HBX warnings (선택)
# ==========================================
ignoreLogs:
  - 'sections-none-'
  - 'missing-icon-hero-'