# ==========================================
# Hugo Academic CV Theme - 다국어 설정 포함
# ==========================================

# Website info
title: Hugo Academic CV Theme
baseURL: 'https://example.com/'

# ==========================================
# LANGUAGE
# ==========================================
defaultContentLanguage: ko
hasCJKLanguage: false
defaultContentLanguageInSubdir: true
removePathAccents: true

# ==========================================
# ADVANCED SETTINGS
# ==========================================
build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep

hugo:
  hasCJKLanguage: false
  removePathAccents: true