# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 전기
    url: /ko/
    weight: 10
    lang: ko
  - name: bio
    url: /en/
    weight: 10
    lang: en
  - name: 경력
    url: /ko/experience/
    weight: 11
    lang: ko
  - name: experience
    url: /en/experience/
    weight: 11
    lang: en
